import { VERSION, PALETTE, CONTROLS, CONTROL_GROUPS, normalize, fromSeed, resolve, svg } from './geometry.mjs?v=2.2.0';

const $ = selector => document.querySelector(selector);
const app = $('#app');
const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const seed = () => crypto.getRandomValues(new Uint32Array(1))[0];
const readLocal = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } };
const writeLocal = (key, value) => { try { localStorage.setItem(key, JSON.stringify(value)); return true; } catch { return false; } };
const fresh = () => ({ ...fromSeed(seed()), growth: false, color: 'cobalt' });
let state = normalize(readLocal('ways-draft', fresh()));
let initial = { ...state }, locks = new Set(), records = [], server = false, initialized = false, savedName = '', toastTimer;
let galleryOffset = 0;
const samples = [
  ['Vase 01', 'Narrow body · closed neck', 186, 'cobalt', {presence:.2,openness:.17,grounding:.4,softness:.9,growth:true}],
  ['Vase 02', 'Wide body · open neck', 841, 'vermilion', {presence:.96,openness:.95,grounding:.5,softness:.72,growth:false}],
  ['Vase 03', 'Soft curve · wide base', 312, 'forest', {presence:.42,openness:.5,grounding:.9,softness:1,growth:false}],
  ['Vase 04', 'Medium body · branch', 952, 'violet', {presence:.62,openness:.23,grounding:.3,softness:.25,growth:true}],
  ['Vase 05', 'Open neck · light base', 64, 'ochre', {presence:.3,openness:.7,grounding:.25,softness:.16,growth:false}],
  ['Vase 06', 'Wide body · soft curve', 675, 'black', {presence:.98,openness:.15,grounding:.7,softness:.98,growth:false}],
  ['Vase 07', 'Narrow body · branch', 193, 'vermilion', {presence:.18,openness:.4,grounding:.55,softness:.7,growth:true}],
  ['Vase 08', 'Wide body · structured curve', 219, 'cobalt', {presence:.95,openness:.4,grounding:.9,softness:.07,growth:false}],
  ['Vase 09', 'Narrow body · light base', 770, 'violet', {presence:.3,openness:.18,grounding:.12,softness:.7,growth:false}],
  ['Vase 10', 'Wide base · branch', 721, 'forest', {presence:.73,openness:.8,grounding:1,softness:.7,growth:true}],
  ['Vase 11', 'Wide body · open neck', 408, 'ochre', {presence:.85,openness:.9,grounding:.2,softness:.7,growth:false}],
];
function sampleState(sample, i) {
  return galleryOffset ? {...fromSeed(sample[2]+galleryOffset*139+i), color:sample[3]} : normalize({...fromSeed(sample[2]),...sample[4],color:sample[3]});
}
function toast(message) {
  clearTimeout(toastTimer); $('#toast').textContent = message; $('#toast').classList.add('visible');
  toastTimer = setTimeout(()=>$('#toast').classList.remove('visible'), 4000);
}
async function api(path, options = {}) {
  const response = await fetch(`api/${path}`, { ...options, headers: {'Content-Type':'application/json',...options.headers} });
  if (!response.ok) { const detail = await response.json().catch(()=>({})); throw new Error(detail.error || 'The studio archive is unavailable. Please try again.'); }
  return response.json();
}
function card(s, title, note, number, attrs='') {
  return `<button class="vase-card" ${attrs} aria-label="Open ${escape(title)}"><div class="card-head"><span>${String(number).padStart(2,'0')}</span><span class="card-arrow" aria-hidden="true">↗</span></div><div class="card-art">${svg(s,{title})}</div><div class="card-foot"><div><h3>${escape(title)}</h3><p>${escape(note)}</p></div></div></button>`;
}
function home() {
  app.innerHTML = `<section class="hero"><div><span class="eyebrow">VASE GENERATOR</span><h1>Create your<br>own vase.</h1></div><div class="hero-right"><p>Adjust the complete set of vase and branch controls. Choose a vase color, save the result, or export it for plotting.</p><p style="margin-top:12px"><strong>Every control maps directly to a parameter in the original sketch.</strong></p><button class="button dark" data-action="create">Create a vase <span aria-hidden="true">↗</span></button></div></section>
  <section class="collection" id="collection"><div class="section-label"><span>STARTING SHAPES</span><p>Select one to edit, or start from scratch.</p></div><div class="gallery">${samples.map((sample,i)=>card(sampleState(sample,i),sample[0],sample[1],i+1,`data-sample="${i}"`)).join('')}<button class="vase-card invitation" data-action="create"><div><h3>Start from<br>scratch</h3><p>Open the editor with a new random vase.</p></div><span class="text-link">Open editor <span aria-hidden="true">↗</span></span></button></div><div class="collection-bottom"><p>These are editable examples generated by the same tool.</p><button class="text-button" data-action="shuffle">Generate more examples ↻</button></div></section>
  <section class="about" id="about"><div><span class="eyebrow">HOW IT WORKS</span><h2>All the controls.<br>One vase<br>construction.</h2></div><div class="about-copy"><p>The editor exposes every form and branch parameter from the original sketch through metaphorical names.</p><p>The vase and branch construction are unchanged. Saving records the complete state, seed, color, SVG, and plot status.</p><p class="small-note">The local Saved vases view is the backend view for this version. It lets you reopen a vase, download its files, and update its plotting status.</p></div></section>`;
}
function lockIcon(locked) { return `<svg viewBox="0 0 12 14" aria-hidden="true"><rect x="2" y="6" width="8" height="7" rx="1"/><path d="${locked?'M3 6V4a3 3 0 0 1 6 0v2':'M3 6V4a3 3 0 0 1 6 0'}"/></svg>`; }
function controlMarkup(control) {
  return `<div class="control"><div class="control-title"><label for="${control.key}">${control.name}</label><button class="lock" data-lock="${control.key}" aria-pressed="${locks.has(control.key)}" aria-label="Lock ${control.name}">${lockIcon(locks.has(control.key))}<span>${locks.has(control.key)?'Locked':'Lock'}</span></button></div><input class="range" id="${control.key}" data-control="${control.key}" type="range" min="0" max="100" value="${Math.round(state[control.key]*100)}" style="--value:${state[control.key]*100}%" aria-label="${control.name}"><div class="range-labels"><span>${control.low}</span><span>${control.high}</span></div></div>`;
}
function controlGroupsMarkup() {
  return CONTROL_GROUPS.map(group => `<section class="control-group ${group.id === 'branch' ? 'branch-group' : ''}"><div class="control-group-heading"><h2>${group.name}</h2>${group.id === 'branch' ? `<label class="growth" for="growth"><span>Show branch</span><input type="checkbox" id="growth" role="switch" ${state.growth?'checked':''}></label>` : ''}</div>${CONTROLS.filter(control => control.group === group.id).map(controlMarkup).join('')}</section>`).join('');
}
function studio() {
  app.innerHTML = `<div class="studio-header"><a class="back-link" href="#collection"><span aria-hidden="true">←</span> Back to examples</a><span class="eyebrow">VASE EDITOR</span></div><section class="studio"><div class="studio-stage"><div class="stage-top"><span><i class="live-dot"></i>LIVE PREVIEW</span><span>210 × 210 MM</span></div><div class="art-sheet"><div id="vase-art" style="width:100%;height:100%"></div><span class="sheet-mark">VASE 2.0</span><span class="sheet-number" id="sheet-number"></span></div><div class="portrait-caption"><h2 id="portrait-title"></h2><p id="portrait-description"></p></div><div class="stage-actions"><button data-action="surprise">↻ &nbsp; Random vase</button><span class="divider"></span><button data-action="reset">Reset</button></div></div><aside class="studio-controls" aria-label="Vase controls"><h1>Shape controls</h1><p class="control-intro">Each slider controls one parameter from the original sketch. Lock any values you want to keep when generating a random vase.</p><div class="controls">${controlGroupsMarkup()}</div><div class="ink-section"><div class="ink-heading"><label>Vase color</label><span id="ink-name"></span></div><div class="swatches" role="group" aria-label="Vase color">${PALETTE.map(c=>`<button class="swatch" data-color="${c.id}" aria-label="${c.name}" title="${c.name}" style="--swatch:${c.hex}" aria-pressed="${state.color===c.id}"></button>`).join('')}</div></div><button class="button dark save-button" data-action="save">Save vase <span aria-hidden="true">↗</span></button><p class="save-hint">Saves all controls, seed, color, and SVG.</p><div class="download-row"><button data-action="svg">Download SVG</button><button data-action="import">Import JSON</button></div><input type="file" id="import-file" accept="application/json,.json" hidden></aside></section>`;
  $('#vase-art').style.cssText = 'width:100%;height:100%;padding:8px 25px 20px;display:flex';
  renderArt();
}
function describe(s) {
  const width = s.presence > .66 ? 'Wide body' : s.presence < .34 ? 'Narrow body' : 'Medium body';
  const neck = s.openness > .66 ? 'open neck' : s.openness < .34 ? 'closed neck' : 'medium neck';
  return `${width} · ${neck} · ${Math.round(30 + s.complexity * 110)} lines`;
}
function renderArt() {
  const artwork = $('#vase-art'); if (!artwork) return;
  artwork.innerHTML = svg(state,{title:savedName||'Vase drawing'}); artwork.firstElementChild.style.cssText = 'width:100%;height:100%';
  $('#ink-name').textContent = PALETTE.find(c=>c.id===state.color).name;
  $('#portrait-title').textContent = savedName || 'Untitled vase';
  $('#portrait-description').textContent = describe(state);
  $('#sheet-number').textContent = `NO. ${state.seed.toString(36).toUpperCase().padStart(6,'0')}`;
  document.querySelectorAll('[data-color]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.color===state.color)));
  for (const c of CONTROLS) {
    const input = $(`#${c.key}`); input.value = Math.round(state[c.key]*100); input.style.setProperty('--value',`${state[c.key]*100}%`);
    input.setAttribute('aria-valuetext',`${input.value}% — ${c.low} to ${c.high}`);
  }
  $('#growth').checked = state.growth;
  $('#growth').setAttribute('aria-label','Show branch');
  writeLocal('ways-draft',state);
}
async function archive() {
  app.innerHTML = '<section class="archive"><p class="eyebrow">LOADING SAVED VASES…</p></section>';
  if (!initialized) return;
  if (server) { try { records = await api('vases'); } catch(error) { toast(error.message); } }
  if (location.hash !== '#saved') return;
  updateCount();
  app.innerHTML = `<section class="archive"><div class="archive-heading"><div><span class="eyebrow">BACKEND VIEW</span><h1>Saved vases</h1><p>${server?'Stored in the local database. Reopen a vase, export its files, or update its plot status.':'Stored in this browser. Download the JSON record to keep a portable copy.'}</p></div><button class="button light" data-action="import">Import JSON <span>↗</span></button><input type="file" id="import-file" accept="application/json,.json" hidden></div>${records.length?`<div class="archive-grid">${records.map((record,i)=>`<article class="archive-item">${card(normalize(record.state),record.name,`${record.id} · ${new Date(record.createdAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})}`,i+1,`data-open="${escape(record.id)}"`)}<div class="archive-tools"><label class="sr-only" for="status-${record.id}">Plot status for ${escape(record.name)}</label><select id="status-${record.id}" data-status="${escape(record.id)}">${['saved','queued','plotted','delivered'].map(status=>`<option value="${status}" ${record.status===status?'selected':''}>${status[0].toUpperCase()+status.slice(1)}</option>`).join('')}</select><div><button data-export-svg="${escape(record.id)}">SVG ↓</button><button data-export-json="${escape(record.id)}">JSON ↓</button></div></div></article>`).join('')}</div>`:`<div class="empty-state"><h2>No saved vases</h2><p>Create a vase and save it to add it here.</p><button class="button dark" data-action="create">Create a vase <span>↗</span></button></div>`}</section>`;
}
function updateCount() { $('#saved-count').textContent = records.length; }
function enterStudio(nextState) { state = normalize(nextState); initial = {...state}; savedName=''; if (location.hash==='#studio') studio(); else location.hash='studio'; }
function route() {
  const route = location.hash;
  $('.header-create').hidden = route === '#studio';
  if (route==='#studio') studio();
  else if(route==='#saved') archive();
  else { home(); if (route==='#collection'||route==='#about') requestAnimationFrame(()=>$(route)?.scrollIntoView({behavior:'instant'})); }
  if (!['#collection','#about'].includes(route)) window.scrollTo(0,0);
}
function makeRecord(name) {
  return { schemaVersion:1, generatorVersion:VERSION, id:`WB-${crypto.randomUUID().slice(0,8).toUpperCase()}`, name, createdAt:new Date().toISOString(), status:'saved', state:{...state}, resolved:resolve(state), paper:{widthMM:210,heightMM:210}, palette:PALETTE.find(c=>c.id===state.color), svg:svg(state,{title:name}) };
}
function download(content, filename, type) { const url=URL.createObjectURL(new Blob([content],{type})); const link=document.createElement('a'); link.href=url; link.download=filename; link.hidden=true; document.body.append(link); link.click(); link.remove(); setTimeout(()=>URL.revokeObjectURL(url),10000); }
function downloadSVG(record) { download(record.svg||svg(record.state,{title:record.name}),`${record.id}.svg`,'image/svg+xml'); toast('Drawing downloaded · 210 × 210 mm'); }
function downloadRecord(record) { download(JSON.stringify(record,null,2),`${record.id}.json`,'application/json'); toast('Vase record downloaded'); }
const actions = {
  create:()=>enterStudio(fresh()),
  shuffle:()=>{galleryOffset++; const y=window.scrollY; home(); window.scrollTo(0,y);},
  surprise:()=>{const next=fromSeed(seed()); for(const c of CONTROLS) if(!locks.has(c.key))state[c.key]=next[c.key]; state.seed=next.seed; savedName='';renderArt();},
  reset:()=>{state={...initial};savedName='';renderArt();toast('Back to where you began');},
  save:async()=>{await storageReady;$('#vase-name').value=savedName; $('#save-location').textContent=server?'This vase will be stored in the local database.':'This vase will be stored in this browser. Download the JSON record for a portable copy.';$('#save-dialog').showModal();$('#vase-name').focus();},
  svg:()=>downloadSVG(makeRecord(savedName||'A form of your own')),
  import:()=>$('#import-file')?.click(),
};
document.addEventListener('click',event=>{
  const button=event.target.closest('button'); if(!button)return;
  if(button.dataset.action) actions[button.dataset.action]?.();
  if(button.dataset.sample!==undefined) {const i=Number(button.dataset.sample);enterStudio(sampleState(samples[i],i));}
  if(button.dataset.color) {state.color=button.dataset.color;renderArt();}
  if(button.dataset.lock) {const key=button.dataset.lock;locks.has(key)?locks.delete(key):locks.add(key);button.setAttribute('aria-pressed',String(locks.has(key)));button.innerHTML=`${lockIcon(locks.has(key))}<span>${locks.has(key)?'Held':'Hold'}</span>`;}
  if(button.dataset.open) {const record=records.find(r=>r.id===button.dataset.open);if(record){enterStudio(record.state);savedName=record.name;renderArt();}}
  if(button.dataset.exportSvg) downloadSVG(records.find(r=>r.id===button.dataset.exportSvg));
  if(button.dataset.exportJson) downloadRecord(records.find(r=>r.id===button.dataset.exportJson));
});
document.addEventListener('input',event=>{if(event.target.dataset.control){state[event.target.dataset.control]=Number(event.target.value)/100;savedName='';renderArt();}});
document.addEventListener('change',async event=>{
  const target=event.target;
  if(target.id==='growth'){state.growth=target.checked;renderArt();}
  if(target.dataset.status){
    const record=records.find(r=>r.id===target.dataset.status),previous=record.status;target.disabled=true;
    try {if(server)await api(`vases/${record.id}`,{method:'PATCH',body:JSON.stringify({status:target.value})});record.status=target.value;if(!server&&!writeLocal('ways-records',records))throw new Error('Browser storage is full. Download your record to keep it.');toast(`Marked as ${target.value}`);}
    catch(error){record.status=previous;target.value=previous;toast(error.message);}finally{target.disabled=false;}
  }
  if(target.id==='import-file'&&target.files[0]){
    try { const file=target.files[0];if(file.size>1000000)throw new Error('Choose a vase record smaller than 1 MB.');const record=JSON.parse(await file.text());if(record.schemaVersion!==1||record.generatorVersion!==VERSION||!record.state||CONTROLS.some(c=>!Number.isFinite(record.state[c.key])||record.state[c.key]<0||record.state[c.key]>1)||!Number.isInteger(record.state.seed)||!PALETTE.some(c=>c.id===record.state.color)||typeof record.state.growth!=='boolean')throw new Error('Choose a compatible Vase 2.2 JSON record.');enterStudio(record.state);savedName=typeof record.name==='string'?record.name.slice(0,60):'';renderArt();toast('Vase imported'); }
    catch(error){toast(error instanceof SyntaxError?'This file is not a valid vase record.':error.message);}
  }
});
$('.dialog-close').addEventListener('click',()=>$('#save-dialog').close());
$('#save-dialog').addEventListener('click',event=>{if(event.target===$('#save-dialog')){const rect=event.target.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)event.target.close();}});
$('#save-form').addEventListener('submit',async event=>{
  event.preventDefault();const name=$('#vase-name').value.trim();if(!name){$('#vase-name').setCustomValidity('Give your form a name.');$('#vase-name').reportValidity();return;}
  const button=event.submitter;button.disabled=true;
  try {let record=makeRecord(name);if(server)record=await api('vases',{method:'POST',body:JSON.stringify(record)});else if(!writeLocal('ways-records',[record,...records]))throw new Error('Browser storage is full. Download your drawing before leaving.');records.unshift(record);updateCount();savedName=name;$('#save-dialog').close();location.hash='saved';toast('Vase saved');}
  catch(error){toast(error.message);}finally{button.disabled=false;}
});
$('#vase-name').addEventListener('input',()=>$('#vase-name').setCustomValidity(''));
window.addEventListener('hashchange',route);
route();
const storageReady=(async()=>{
  try {const health=await api('health');server=health.service==='ways-of-being';} catch {server=false;}
  if(server){try{records=await api('vases');}catch(error){toast(error.message);}}
  else{records=readLocal('ways-records',[]);if(!Array.isArray(records))records=[];}
  initialized=true;updateCount();if(location.hash==='#saved')archive();
})();
